"""
Type stubs for sunrise_signal_adapter module
This helps VS Code resolve imports and reduces warnings
"""

from typing import Optional, Dict, List, Any
from datetime import datetime
import pandas as pd
import numpy as np

class SignalType:
    BUY: str
    SELL: str
    CLOSE_BUY: str
    CLOSE_SELL: str
    HOLD: str

class TradingSignal:
    def __init__(self,
                 symbol: str,
                 signal_type: str,
                 confidence: float,
                 entry_price: Optional[float] = None,
                 stop_loss: Optional[float] = None,
                 take_profit: Optional[float] = None,
                 position_size: Optional[float] = None,
                 timestamp: Optional[datetime] = None,
                 metadata: Optional[Dict] = None) -> None: ...
    
    def to_dict(self) -> Dict: ...
    def __str__(self) -> str: ...

class SunriseSignalGenerator:
    def __init__(self, symbol: str, strategy_class: Any, logger: Any = None) -> None: ...
    def update_data(self, rates: np.ndarray) -> bool: ...
    def calculate_indicators(self) -> Dict: ...
    def generate_signal(self) -> Optional[TradingSignal]: ...

class MultiSymbolSignalManager:
    def __init__(self, logger: Any = None) -> None: ...
    def add_symbol(self, symbol: str) -> bool: ...
    def update_market_data(self, symbol: str, rates: np.ndarray) -> bool: ...
    def get_signals(self) -> List[TradingSignal]: ...
    def get_signal(self, symbol: str) -> Optional[TradingSignal]: ...

class MT5DataProvider:
    def __init__(self, logger: Any = None) -> None: ...
    def connect(self) -> bool: ...
    def get_rates(self, symbol: str, timeframe: int, count: int = 100) -> Optional[np.ndarray]: ...
    def get_tick(self, symbol: str) -> Optional[Dict]: ...
    def disconnect(self) -> None: ...

def test_signal_generation() -> bool: ...